// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seven_day.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_seven_5fday_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_seven_5fday_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_seven_5fday_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_seven_5fday_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_seven_5fday_2eproto;
namespace fluyii_game {
class MsgFriend;
class MsgFriendDefaultTypeInternal;
extern MsgFriendDefaultTypeInternal _MsgFriend_default_instance_;
class MsgInt64List;
class MsgInt64ListDefaultTypeInternal;
extern MsgInt64ListDefaultTypeInternal _MsgInt64List_default_instance_;
class MsgPlayer;
class MsgPlayerDefaultTypeInternal;
extern MsgPlayerDefaultTypeInternal _MsgPlayer_default_instance_;
class MsgSevenResp;
class MsgSevenRespDefaultTypeInternal;
extern MsgSevenRespDefaultTypeInternal _MsgSevenResp_default_instance_;
}  // namespace fluyii_game
PROTOBUF_NAMESPACE_OPEN
template<> ::fluyii_game::MsgFriend* Arena::CreateMaybeMessage<::fluyii_game::MsgFriend>(Arena*);
template<> ::fluyii_game::MsgInt64List* Arena::CreateMaybeMessage<::fluyii_game::MsgInt64List>(Arena*);
template<> ::fluyii_game::MsgPlayer* Arena::CreateMaybeMessage<::fluyii_game::MsgPlayer>(Arena*);
template<> ::fluyii_game::MsgSevenResp* Arena::CreateMaybeMessage<::fluyii_game::MsgSevenResp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace fluyii_game {

// ===================================================================

class MsgInt64List :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fluyii_game.MsgInt64List) */ {
 public:
  MsgInt64List();
  virtual ~MsgInt64List();

  MsgInt64List(const MsgInt64List& from);
  MsgInt64List(MsgInt64List&& from) noexcept
    : MsgInt64List() {
    *this = ::std::move(from);
  }

  inline MsgInt64List& operator=(const MsgInt64List& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgInt64List& operator=(MsgInt64List&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgInt64List& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgInt64List* internal_default_instance() {
    return reinterpret_cast<const MsgInt64List*>(
               &_MsgInt64List_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MsgInt64List& a, MsgInt64List& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgInt64List* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgInt64List* New() const final {
    return CreateMaybeMessage<MsgInt64List>(nullptr);
  }

  MsgInt64List* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgInt64List>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgInt64List& from);
  void MergeFrom(const MsgInt64List& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgInt64List* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fluyii_game.MsgInt64List";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_seven_5fday_2eproto);
    return ::descriptor_table_seven_5fday_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdsFieldNumber = 1,
  };
  // repeated int64 ids = 1;
  int ids_size() const;
  private:
  int _internal_ids_size() const;
  public:
  void clear_ids();
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_ids(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      _internal_ids() const;
  void _internal_add_ids(::PROTOBUF_NAMESPACE_ID::int64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      _internal_mutable_ids();
  public:
  ::PROTOBUF_NAMESPACE_ID::int64 ids(int index) const;
  void set_ids(int index, ::PROTOBUF_NAMESPACE_ID::int64 value);
  void add_ids(::PROTOBUF_NAMESPACE_ID::int64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
      ids() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
      mutable_ids();

  // @@protoc_insertion_point(class_scope:fluyii_game.MsgInt64List)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 > ids_;
  friend struct ::TableStruct_seven_5fday_2eproto;
};
// -------------------------------------------------------------------

class MsgPlayer :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fluyii_game.MsgPlayer) */ {
 public:
  MsgPlayer();
  virtual ~MsgPlayer();

  MsgPlayer(const MsgPlayer& from);
  MsgPlayer(MsgPlayer&& from) noexcept
    : MsgPlayer() {
    *this = ::std::move(from);
  }

  inline MsgPlayer& operator=(const MsgPlayer& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgPlayer& operator=(MsgPlayer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgPlayer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgPlayer* internal_default_instance() {
    return reinterpret_cast<const MsgPlayer*>(
               &_MsgPlayer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(MsgPlayer& a, MsgPlayer& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgPlayer* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgPlayer* New() const final {
    return CreateMaybeMessage<MsgPlayer>(nullptr);
  }

  MsgPlayer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgPlayer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgPlayer& from);
  void MergeFrom(const MsgPlayer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgPlayer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fluyii_game.MsgPlayer";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_seven_5fday_2eproto);
    return ::descriptor_table_seven_5fday_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerNameFieldNumber = 2,
    kPlayerIdFieldNumber = 1,
  };
  // required string player_name = 2;
  bool has_player_name() const;
  private:
  bool _internal_has_player_name() const;
  public:
  void clear_player_name();
  const std::string& player_name() const;
  void set_player_name(const std::string& value);
  void set_player_name(std::string&& value);
  void set_player_name(const char* value);
  void set_player_name(const char* value, size_t size);
  std::string* mutable_player_name();
  std::string* release_player_name();
  void set_allocated_player_name(std::string* player_name);
  private:
  const std::string& _internal_player_name() const;
  void _internal_set_player_name(const std::string& value);
  std::string* _internal_mutable_player_name();
  public:

  // required int64 player_id = 1;
  bool has_player_id() const;
  private:
  bool _internal_has_player_id() const;
  public:
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::int64 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:fluyii_game.MsgPlayer)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr player_name_;
  ::PROTOBUF_NAMESPACE_ID::int64 player_id_;
  friend struct ::TableStruct_seven_5fday_2eproto;
};
// -------------------------------------------------------------------

class MsgFriend :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fluyii_game.MsgFriend) */ {
 public:
  MsgFriend();
  virtual ~MsgFriend();

  MsgFriend(const MsgFriend& from);
  MsgFriend(MsgFriend&& from) noexcept
    : MsgFriend() {
    *this = ::std::move(from);
  }

  inline MsgFriend& operator=(const MsgFriend& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgFriend& operator=(MsgFriend&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgFriend& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgFriend* internal_default_instance() {
    return reinterpret_cast<const MsgFriend*>(
               &_MsgFriend_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MsgFriend& a, MsgFriend& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgFriend* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgFriend* New() const final {
    return CreateMaybeMessage<MsgFriend>(nullptr);
  }

  MsgFriend* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgFriend>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgFriend& from);
  void MergeFrom(const MsgFriend& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgFriend* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fluyii_game.MsgFriend";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_seven_5fday_2eproto);
    return ::descriptor_table_seven_5fday_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFriendIntimateFieldNumber = 1,
    kLvFieldNumber = 2,
  };
  // required int32 friend_intimate = 1;
  bool has_friend_intimate() const;
  private:
  bool _internal_has_friend_intimate() const;
  public:
  void clear_friend_intimate();
  ::PROTOBUF_NAMESPACE_ID::int32 friend_intimate() const;
  void set_friend_intimate(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_friend_intimate() const;
  void _internal_set_friend_intimate(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // required int32 lv = 2;
  bool has_lv() const;
  private:
  bool _internal_has_lv() const;
  public:
  void clear_lv();
  ::PROTOBUF_NAMESPACE_ID::int32 lv() const;
  void set_lv(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_lv() const;
  void _internal_set_lv(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:fluyii_game.MsgFriend)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::int32 friend_intimate_;
  ::PROTOBUF_NAMESPACE_ID::int32 lv_;
  friend struct ::TableStruct_seven_5fday_2eproto;
};
// -------------------------------------------------------------------

class MsgSevenResp :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:fluyii_game.MsgSevenResp) */ {
 public:
  MsgSevenResp();
  virtual ~MsgSevenResp();

  MsgSevenResp(const MsgSevenResp& from);
  MsgSevenResp(MsgSevenResp&& from) noexcept
    : MsgSevenResp() {
    *this = ::std::move(from);
  }

  inline MsgSevenResp& operator=(const MsgSevenResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline MsgSevenResp& operator=(MsgSevenResp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MsgSevenResp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MsgSevenResp* internal_default_instance() {
    return reinterpret_cast<const MsgSevenResp*>(
               &_MsgSevenResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(MsgSevenResp& a, MsgSevenResp& b) {
    a.Swap(&b);
  }
  inline void Swap(MsgSevenResp* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MsgSevenResp* New() const final {
    return CreateMaybeMessage<MsgSevenResp>(nullptr);
  }

  MsgSevenResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MsgSevenResp>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MsgSevenResp& from);
  void MergeFrom(const MsgSevenResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MsgSevenResp* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "fluyii_game.MsgSevenResp";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_seven_5fday_2eproto);
    return ::descriptor_table_seven_5fday_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecordsFieldNumber = 3,
    kOthersFieldNumber = 4,
    kPlayerNameFieldNumber = 2,
    kFriendFieldNumber = 5,
    kMoneyFieldNumber = 6,
    kPlayerIdFieldNumber = 1,
  };
  // repeated int32 records = 3;
  int records_size() const;
  private:
  int _internal_records_size() const;
  public:
  void clear_records();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_records(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_records() const;
  void _internal_add_records(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_records();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 records(int index) const;
  void set_records(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_records(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      records() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_records();

  // repeated .fluyii_game.MsgPlayer others = 4;
  int others_size() const;
  private:
  int _internal_others_size() const;
  public:
  void clear_others();
  ::fluyii_game::MsgPlayer* mutable_others(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fluyii_game::MsgPlayer >*
      mutable_others();
  private:
  const ::fluyii_game::MsgPlayer& _internal_others(int index) const;
  ::fluyii_game::MsgPlayer* _internal_add_others();
  public:
  const ::fluyii_game::MsgPlayer& others(int index) const;
  ::fluyii_game::MsgPlayer* add_others();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fluyii_game::MsgPlayer >&
      others() const;

  // required string player_name = 2;
  bool has_player_name() const;
  private:
  bool _internal_has_player_name() const;
  public:
  void clear_player_name();
  const std::string& player_name() const;
  void set_player_name(const std::string& value);
  void set_player_name(std::string&& value);
  void set_player_name(const char* value);
  void set_player_name(const char* value, size_t size);
  std::string* mutable_player_name();
  std::string* release_player_name();
  void set_allocated_player_name(std::string* player_name);
  private:
  const std::string& _internal_player_name() const;
  void _internal_set_player_name(const std::string& value);
  std::string* _internal_mutable_player_name();
  public:

  // required .fluyii_game.MsgFriend friend = 5;
  bool has_friend_() const;
  private:
  bool _internal_has_friend_() const;
  public:
  void clear_friend_();
  const ::fluyii_game::MsgFriend& friend_() const;
  ::fluyii_game::MsgFriend* release_friend_();
  ::fluyii_game::MsgFriend* mutable_friend_();
  void set_allocated_friend_(::fluyii_game::MsgFriend* friend_);
  private:
  const ::fluyii_game::MsgFriend& _internal_friend_() const;
  ::fluyii_game::MsgFriend* _internal_mutable_friend_();
  public:

  // required double money = 6;
  bool has_money() const;
  private:
  bool _internal_has_money() const;
  public:
  void clear_money();
  double money() const;
  void set_money(double value);
  private:
  double _internal_money() const;
  void _internal_set_money(double value);
  public:

  // required int32 player_id = 1;
  bool has_player_id() const;
  private:
  bool _internal_has_player_id() const;
  public:
  void clear_player_id();
  ::PROTOBUF_NAMESPACE_ID::int32 player_id() const;
  void set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_player_id() const;
  void _internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:fluyii_game.MsgSevenResp)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > records_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fluyii_game::MsgPlayer > others_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr player_name_;
  ::fluyii_game::MsgFriend* friend__;
  double money_;
  ::PROTOBUF_NAMESPACE_ID::int32 player_id_;
  friend struct ::TableStruct_seven_5fday_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MsgInt64List

// repeated int64 ids = 1;
inline int MsgInt64List::_internal_ids_size() const {
  return ids_.size();
}
inline int MsgInt64List::ids_size() const {
  return _internal_ids_size();
}
inline void MsgInt64List::clear_ids() {
  ids_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgInt64List::_internal_ids(int index) const {
  return ids_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgInt64List::ids(int index) const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgInt64List.ids)
  return _internal_ids(index);
}
inline void MsgInt64List::set_ids(int index, ::PROTOBUF_NAMESPACE_ID::int64 value) {
  ids_.Set(index, value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgInt64List.ids)
}
inline void MsgInt64List::_internal_add_ids(::PROTOBUF_NAMESPACE_ID::int64 value) {
  ids_.Add(value);
}
inline void MsgInt64List::add_ids(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_add_ids(value);
  // @@protoc_insertion_point(field_add:fluyii_game.MsgInt64List.ids)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
MsgInt64List::_internal_ids() const {
  return ids_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >&
MsgInt64List::ids() const {
  // @@protoc_insertion_point(field_list:fluyii_game.MsgInt64List.ids)
  return _internal_ids();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
MsgInt64List::_internal_mutable_ids() {
  return &ids_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int64 >*
MsgInt64List::mutable_ids() {
  // @@protoc_insertion_point(field_mutable_list:fluyii_game.MsgInt64List.ids)
  return _internal_mutable_ids();
}

// -------------------------------------------------------------------

// MsgPlayer

// required int64 player_id = 1;
inline bool MsgPlayer::_internal_has_player_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MsgPlayer::has_player_id() const {
  return _internal_has_player_id();
}
inline void MsgPlayer::clear_player_id() {
  player_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgPlayer::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MsgPlayer::player_id() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgPlayer.player_id)
  return _internal_player_id();
}
inline void MsgPlayer::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000002u;
  player_id_ = value;
}
inline void MsgPlayer::set_player_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgPlayer.player_id)
}

// required string player_name = 2;
inline bool MsgPlayer::_internal_has_player_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MsgPlayer::has_player_name() const {
  return _internal_has_player_name();
}
inline void MsgPlayer::clear_player_name() {
  player_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MsgPlayer::player_name() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgPlayer.player_name)
  return _internal_player_name();
}
inline void MsgPlayer::set_player_name(const std::string& value) {
  _internal_set_player_name(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgPlayer.player_name)
}
inline std::string* MsgPlayer::mutable_player_name() {
  // @@protoc_insertion_point(field_mutable:fluyii_game.MsgPlayer.player_name)
  return _internal_mutable_player_name();
}
inline const std::string& MsgPlayer::_internal_player_name() const {
  return player_name_.GetNoArena();
}
inline void MsgPlayer::_internal_set_player_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MsgPlayer::set_player_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fluyii_game.MsgPlayer.player_name)
}
inline void MsgPlayer::set_player_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fluyii_game.MsgPlayer.player_name)
}
inline void MsgPlayer::set_player_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fluyii_game.MsgPlayer.player_name)
}
inline std::string* MsgPlayer::_internal_mutable_player_name() {
  _has_bits_[0] |= 0x00000001u;
  return player_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MsgPlayer::release_player_name() {
  // @@protoc_insertion_point(field_release:fluyii_game.MsgPlayer.player_name)
  if (!has_player_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return player_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MsgPlayer::set_allocated_player_name(std::string* player_name) {
  if (player_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  player_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), player_name);
  // @@protoc_insertion_point(field_set_allocated:fluyii_game.MsgPlayer.player_name)
}

// -------------------------------------------------------------------

// MsgFriend

// required int32 friend_intimate = 1;
inline bool MsgFriend::_internal_has_friend_intimate() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MsgFriend::has_friend_intimate() const {
  return _internal_has_friend_intimate();
}
inline void MsgFriend::clear_friend_intimate() {
  friend_intimate_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgFriend::_internal_friend_intimate() const {
  return friend_intimate_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgFriend::friend_intimate() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgFriend.friend_intimate)
  return _internal_friend_intimate();
}
inline void MsgFriend::_internal_set_friend_intimate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000001u;
  friend_intimate_ = value;
}
inline void MsgFriend::set_friend_intimate(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_friend_intimate(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgFriend.friend_intimate)
}

// required int32 lv = 2;
inline bool MsgFriend::_internal_has_lv() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MsgFriend::has_lv() const {
  return _internal_has_lv();
}
inline void MsgFriend::clear_lv() {
  lv_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgFriend::_internal_lv() const {
  return lv_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgFriend::lv() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgFriend.lv)
  return _internal_lv();
}
inline void MsgFriend::_internal_set_lv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  lv_ = value;
}
inline void MsgFriend::set_lv(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_lv(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgFriend.lv)
}

// -------------------------------------------------------------------

// MsgSevenResp

// required int32 player_id = 1;
inline bool MsgSevenResp::_internal_has_player_id() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool MsgSevenResp::has_player_id() const {
  return _internal_has_player_id();
}
inline void MsgSevenResp::clear_player_id() {
  player_id_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgSevenResp::_internal_player_id() const {
  return player_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgSevenResp::player_id() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.player_id)
  return _internal_player_id();
}
inline void MsgSevenResp::_internal_set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  player_id_ = value;
}
inline void MsgSevenResp::set_player_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgSevenResp.player_id)
}

// required string player_name = 2;
inline bool MsgSevenResp::_internal_has_player_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MsgSevenResp::has_player_name() const {
  return _internal_has_player_name();
}
inline void MsgSevenResp::clear_player_name() {
  player_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MsgSevenResp::player_name() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.player_name)
  return _internal_player_name();
}
inline void MsgSevenResp::set_player_name(const std::string& value) {
  _internal_set_player_name(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgSevenResp.player_name)
}
inline std::string* MsgSevenResp::mutable_player_name() {
  // @@protoc_insertion_point(field_mutable:fluyii_game.MsgSevenResp.player_name)
  return _internal_mutable_player_name();
}
inline const std::string& MsgSevenResp::_internal_player_name() const {
  return player_name_.GetNoArena();
}
inline void MsgSevenResp::_internal_set_player_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MsgSevenResp::set_player_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:fluyii_game.MsgSevenResp.player_name)
}
inline void MsgSevenResp::set_player_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:fluyii_game.MsgSevenResp.player_name)
}
inline void MsgSevenResp::set_player_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  player_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:fluyii_game.MsgSevenResp.player_name)
}
inline std::string* MsgSevenResp::_internal_mutable_player_name() {
  _has_bits_[0] |= 0x00000001u;
  return player_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MsgSevenResp::release_player_name() {
  // @@protoc_insertion_point(field_release:fluyii_game.MsgSevenResp.player_name)
  if (!has_player_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return player_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MsgSevenResp::set_allocated_player_name(std::string* player_name) {
  if (player_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  player_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), player_name);
  // @@protoc_insertion_point(field_set_allocated:fluyii_game.MsgSevenResp.player_name)
}

// repeated int32 records = 3;
inline int MsgSevenResp::_internal_records_size() const {
  return records_.size();
}
inline int MsgSevenResp::records_size() const {
  return _internal_records_size();
}
inline void MsgSevenResp::clear_records() {
  records_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgSevenResp::_internal_records(int index) const {
  return records_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 MsgSevenResp::records(int index) const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.records)
  return _internal_records(index);
}
inline void MsgSevenResp::set_records(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  records_.Set(index, value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgSevenResp.records)
}
inline void MsgSevenResp::_internal_add_records(::PROTOBUF_NAMESPACE_ID::int32 value) {
  records_.Add(value);
}
inline void MsgSevenResp::add_records(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_records(value);
  // @@protoc_insertion_point(field_add:fluyii_game.MsgSevenResp.records)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgSevenResp::_internal_records() const {
  return records_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
MsgSevenResp::records() const {
  // @@protoc_insertion_point(field_list:fluyii_game.MsgSevenResp.records)
  return _internal_records();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgSevenResp::_internal_mutable_records() {
  return &records_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
MsgSevenResp::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:fluyii_game.MsgSevenResp.records)
  return _internal_mutable_records();
}

// repeated .fluyii_game.MsgPlayer others = 4;
inline int MsgSevenResp::_internal_others_size() const {
  return others_.size();
}
inline int MsgSevenResp::others_size() const {
  return _internal_others_size();
}
inline void MsgSevenResp::clear_others() {
  others_.Clear();
}
inline ::fluyii_game::MsgPlayer* MsgSevenResp::mutable_others(int index) {
  // @@protoc_insertion_point(field_mutable:fluyii_game.MsgSevenResp.others)
  return others_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fluyii_game::MsgPlayer >*
MsgSevenResp::mutable_others() {
  // @@protoc_insertion_point(field_mutable_list:fluyii_game.MsgSevenResp.others)
  return &others_;
}
inline const ::fluyii_game::MsgPlayer& MsgSevenResp::_internal_others(int index) const {
  return others_.Get(index);
}
inline const ::fluyii_game::MsgPlayer& MsgSevenResp::others(int index) const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.others)
  return _internal_others(index);
}
inline ::fluyii_game::MsgPlayer* MsgSevenResp::_internal_add_others() {
  return others_.Add();
}
inline ::fluyii_game::MsgPlayer* MsgSevenResp::add_others() {
  // @@protoc_insertion_point(field_add:fluyii_game.MsgSevenResp.others)
  return _internal_add_others();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::fluyii_game::MsgPlayer >&
MsgSevenResp::others() const {
  // @@protoc_insertion_point(field_list:fluyii_game.MsgSevenResp.others)
  return others_;
}

// required .fluyii_game.MsgFriend friend = 5;
inline bool MsgSevenResp::_internal_has_friend_() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || friend__ != nullptr);
  return value;
}
inline bool MsgSevenResp::has_friend_() const {
  return _internal_has_friend_();
}
inline void MsgSevenResp::clear_friend_() {
  if (friend__ != nullptr) friend__->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::fluyii_game::MsgFriend& MsgSevenResp::_internal_friend_() const {
  const ::fluyii_game::MsgFriend* p = friend__;
  return p != nullptr ? *p : *reinterpret_cast<const ::fluyii_game::MsgFriend*>(
      &::fluyii_game::_MsgFriend_default_instance_);
}
inline const ::fluyii_game::MsgFriend& MsgSevenResp::friend_() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.friend)
  return _internal_friend_();
}
inline ::fluyii_game::MsgFriend* MsgSevenResp::release_friend_() {
  // @@protoc_insertion_point(field_release:fluyii_game.MsgSevenResp.friend)
  _has_bits_[0] &= ~0x00000002u;
  ::fluyii_game::MsgFriend* temp = friend__;
  friend__ = nullptr;
  return temp;
}
inline ::fluyii_game::MsgFriend* MsgSevenResp::_internal_mutable_friend_() {
  _has_bits_[0] |= 0x00000002u;
  if (friend__ == nullptr) {
    auto* p = CreateMaybeMessage<::fluyii_game::MsgFriend>(GetArenaNoVirtual());
    friend__ = p;
  }
  return friend__;
}
inline ::fluyii_game::MsgFriend* MsgSevenResp::mutable_friend_() {
  // @@protoc_insertion_point(field_mutable:fluyii_game.MsgSevenResp.friend)
  return _internal_mutable_friend_();
}
inline void MsgSevenResp::set_allocated_friend_(::fluyii_game::MsgFriend* friend_) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete friend__;
  }
  if (friend_) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena = nullptr;
    if (message_arena != submessage_arena) {
      friend_ = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, friend_, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  friend__ = friend_;
  // @@protoc_insertion_point(field_set_allocated:fluyii_game.MsgSevenResp.friend)
}

// required double money = 6;
inline bool MsgSevenResp::_internal_has_money() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MsgSevenResp::has_money() const {
  return _internal_has_money();
}
inline void MsgSevenResp::clear_money() {
  money_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double MsgSevenResp::_internal_money() const {
  return money_;
}
inline double MsgSevenResp::money() const {
  // @@protoc_insertion_point(field_get:fluyii_game.MsgSevenResp.money)
  return _internal_money();
}
inline void MsgSevenResp::_internal_set_money(double value) {
  _has_bits_[0] |= 0x00000004u;
  money_ = value;
}
inline void MsgSevenResp::set_money(double value) {
  _internal_set_money(value);
  // @@protoc_insertion_point(field_set:fluyii_game.MsgSevenResp.money)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace fluyii_game

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_seven_5fday_2eproto
